# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: Fabulor.Fabulor
PackageVersion: 1.0.6
PackageLocale: en-GB
Publisher: Fabulor
PublisherUrl: https://github.com/Fabulor
PackageName: Fabulor
PackageUrl: https://github.com/Fabulor/fabulor
License: GPL-3.0-only
LicenseUrl: https://github.com/Fabulor/fabulor/blob/main/Licence.md
ShortDescription: A modern GTK4 IRC client for Windows 11 with Python, Tcl and C# add-ons.
Moniker: fabulor
Tags:
- irc
- chat
- gtk4
ReleaseNotesUrl: https://github.com/Fabulor/fabulor/releases/tag/v1.0.6
ManifestType: defaultLocale
ManifestVersion: 1.10.0
